# Generated by Django 3.1.2 on 2020-10-18 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('channel_id', models.CharField(max_length=25)),
                ('channel_username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_count', models.IntegerField(blank=True, default=0, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('video_count', models.IntegerField(default=0)),
                ('channel_registered', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statsgetter.youtubechannel')),
            ],
        ),
    ]
