# Generated by Django 3.1.2 on 2020-10-19 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsgetter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='channel_id',
            new_name='channel',
        ),
        migrations.RemoveField(
            model_name='youtubechannel',
            name='channel_username',
        ),
    ]
