# Generated by Django 3.1.2 on 2020-10-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsgetter', '0003_auto_20201020_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='transaction_id',
            field=models.IntegerField(default=0),
        ),
    ]
